### ISSUE TITLE
Fix Firefox and Safari Specific Styling Bugs

### ISSUE THREAD

**Issue by shrirambalaji** [b2l-chennai/b2l-chennai.github.io#12]
<img width="1279" alt="screen shot 2018-04-14 at 8 29 52 pm" src="https://user-images.githubusercontent.com/11358903/38769600-157b901e-4023-11e8-80c4-b04518c6904f.png">

The sidebar table-cell behavior seems to be different across different browsers. Chrome renders it as expected, but thats the not the case for Firefox and Safari. 

This needs to be fixed.

**Comment by iMagesh** [comment]
![image 15-04-18 at 3 44 pm](https://user-images.githubusercontent.com/84182/38777438-9df2cb72-40c5-11e8-8ac8-6e9904ddfc8e.jpg)

This is how I saw it on my Macbook laptop - Safari browser.

**Comment by shrirambalaji** [comment]
This should now be addressed in #11. Let me know if there are still issues with that.
